export const ingredientsDictionary = {
    Honey: { sugarPercentage: 79.6, volumeContribution: 15.5, name: 'Honey' },
    'Table Sugar': { sugarPercentage: 99.8, volumeContribution: 0.02, name: 'Table Sugar' },
    Apples: { sugarPercentage: 11.58, volumeContribution: 84.6, name: 'Apples' },
    Apricot: { sugarPercentage: 9.17, volumeContribution: 84.6, name: 'Apricot' },
    Banana: { sugarPercentage: 13.85, volumeContribution: 74.9, name: 'Banana' },
    Blackberry: { sugarPercentage: 7.86, volumeContribution: 82.5, name: 'Blackberry' },
    Blueberry: { sugarPercentage: 9.36, volumeContribution: 84.2, name: 'Blueberry' },
    Boysenberry: { sugarPercentage: 6.23, volumeContribution: 85.9, name: 'Boysenberry' },
    Cantaloupe: { sugarPercentage: 7.89, volumeContribution: 90.2, name: 'Cantaloupe' },
    Carrot: { sugarPercentage: 4.59, volumeContribution: 88.3, name: 'Carrot' },
    'Cherry, Sweet': { sugarPercentage: 13.63, volumeContribution: 82.2, name: 'Cherry, Sweet' },
    'Cherry, Tart': { sugarPercentage: 8.2, volumeContribution: 86.1, name: 'Cherry, Tart' },
    Cranberry: { sugarPercentage: 8.44, volumeContribution: 87.3, name: 'Cranberry' },
    'Currant, Black': { sugarPercentage: 9.3, volumeContribution: 82, name: 'Currant, Black' },
    'Currant, Red': { sugarPercentage: 6.69, volumeContribution: 84, name: 'Currant, Red' },
    'Dates, Dried': { sugarPercentage: 64.7, volumeContribution: 20.9, name: 'Dates, Dried' },
    Elderberry: { sugarPercentage: 6.11, volumeContribution: 79.8, name: 'Elderberry' },
    Figs: { sugarPercentage: 14.05, volumeContribution: 79.1, name: 'Figs' },
    'Figs, Dried': { sugarPercentage: 47.9, volumeContribution: 30, name: 'Figs, Dried' },
    Gooseberry: { sugarPercentage: 11, volumeContribution: 87.9, name: 'Gooseberry' },
    Grapefruit: { sugarPercentage: 6.1, volumeContribution: 90.67, name: 'Grapefruit' },
    'Grapes, Concord': { sugarPercentage: 8.89, volumeContribution: 83, name: 'Grapes, Concord' },
    Guava: { sugarPercentage: 7.56, volumeContribution: 80.8, name: 'Guava' },
    'Honeydew Melon': { sugarPercentage: 8.12, volumeContribution: 89.8, name: 'Honeydew Melon' },
    Jackfruit: { sugarPercentage: 18.75, volumeContribution: 73.5, name: 'Jackfruit' },
    Kiwi: { sugarPercentage: 10.9, volumeContribution: 83.9, name: 'Kiwi' },
    'Lemon Juice': { sugarPercentage: 2.36, volumeContribution: 92.3, name: 'Lemon Juice' },
    'Lime Juice': { sugarPercentage: 1.35, volumeContribution: 90.8, name: 'Lime Juice' },
    Lychee: { sugarPercentage: 16.1, volumeContribution: 81.8, name: 'Lychee' },
    Mango: { sugarPercentage: 12.55, volumeContribution: 83.5, name: 'Mango' },
    'Maple Syrup': { sugarPercentage: 66, volumeContribution: 32.2, name: 'Maple Syrup' },
    Mulberry: { sugarPercentage: 10.8, volumeContribution: 87.7, name: 'Mulberry' },
    Nectarine: { sugarPercentage: 7.76, volumeContribution: 87.6, name: 'Nectarine' },
    'Orange Juice': { sugarPercentage: 9.39, volumeContribution: 88.5, name: 'Orange Juice' },
    Papaya: { sugarPercentage: 7.11, volumeContribution: 88.1, name: 'Papaya' },
    Passionfruit: { sugarPercentage: 11.15, volumeContribution: 72.9, name: 'Passionfruit' },
    Peaches: { sugarPercentage: 8.53, volumeContribution: 88.3, name: 'Peaches' },
    Pear: { sugarPercentage: 9.15, volumeContribution: 85.43, name: 'Pear' },
    Persimmon: { sugarPercentage: 13.25, volumeContribution: 80.3, name: 'Persimmon' },
    Pineapple: { sugarPercentage: 10.39, volumeContribution: 86, name: 'Pineapple' },
    Plum: { sugarPercentage: 9.86, volumeContribution: 87.2, name: 'Plum' },
    Pomegranate: { sugarPercentage: 12.6, volumeContribution: 77.9, name: 'Pomegranate' },
    'Prickly Pear': { sugarPercentage: 11, volumeContribution: 87.6, name: 'Prickly Pear' },
    Prunes: { sugarPercentage: 41.05, volumeContribution: 30.9, name: 'Prunes' },
    Raisins: { sugarPercentage: 68.35, volumeContribution: 16.6, name: 'Raisins' },
    Raspberry: { sugarPercentage: 4.98, volumeContribution: 85.8, name: 'Raspberry' },
    Rhubarb: { sugarPercentage: 1.03, volumeContribution: 93.6, name: 'Rhubarb' },
    Strawberry: { sugarPercentage: 5.45, volumeContribution: 91, name: 'Strawberry' },
    Tangerine: { sugarPercentage: 8.58, volumeContribution: 85.2, name: 'Tangerine' },
    Tomato: { sugarPercentage: 2.7, volumeContribution: 94.33, name: 'Tomato' },
    Watermelon: { sugarPercentage: 7.6, volumeContribution: 91.4, name: 'Watermelon' },
    Custom: { sugarPercentage: 0.0, volumeContribution: 0.0, name: 'Custom' },
};

export const ingredientsArray = [
    { name: 'Honey', sugarPercentage: 79.6, volumeContribution: 15.5 },
    { name: 'Table Sugar', sugarPercentage: 99.8, volumeContribution: 0.02 },
    { name: 'Apples', sugarPercentage: 11.58, volumeContribution: 84.6 },
    { name: 'Apricot', sugarPercentage: 9.17, volumeContribution: 84.6 },
    { name: 'Banana', sugarPercentage: 13.85, volumeContribution: 74.9 },
    { name: 'Blackberry', sugarPercentage: 7.86, volumeContribution: 82.5 },
    { name: 'Blueberry', sugarPercentage: 9.36, volumeContribution: 84.2 },
    { name: 'Boysenberry', sugarPercentage: 6.23, volumeContribution: 85.9 },
    { name: 'Cantaloupe', sugarPercentage: 7.89, volumeContribution: 90.2 },
    { name: 'Carrot', sugarPercentage: 4.59, volumeContribution: 88.3 },
    { name: 'Cherry, Sweet', sugarPercentage: 13.63, volumeContribution: 82.2 },
    { name: 'Cherry, Tart', sugarPercentage: 8.2, volumeContribution: 86.1 },
    { name: 'Cranberry', sugarPercentage: 8.44, volumeContribution: 87.3 },
    { name: 'Currant, Black', sugarPercentage: 9.3, volumeContribution: 82 },
    { name: 'Currant, Red', sugarPercentage: 6.69, volumeContribution: 84 },
    { name: 'Dates, Dried', sugarPercentage: 64.7, volumeContribution: 20.9 },
    { name: 'Elderberry', sugarPercentage: 6.11, volumeContribution: 79.8 },
    { name: 'Figs', sugarPercentage: 14.05, volumeContribution: 79.1 },
    { name: 'Figs, Dried', sugarPercentage: 47.9, volumeContribution: 30 },
    { name: 'Gooseberry', sugarPercentage: 11, volumeContribution: 87.9 },
    { name: 'Grapefruit', sugarPercentage: 6.1, volumeContribution: 90.67 },
    { name: 'Grapes, Concord', sugarPercentage: 8.89, volumeContribution: 83 },
    { name: 'Guava', sugarPercentage: 7.56, volumeContribution: 80.8 },
    { name: 'Honeydew Melon', sugarPercentage: 8.12, volumeContribution: 89.8 },
    { name: 'Jackfruit', sugarPercentage: 18.75, volumeContribution: 73.5 },
    { name: 'Kiwi', sugarPercentage: 10.9, volumeContribution: 83.9 },
    { name: 'Lemon Juice', sugarPercentage: 2.36, volumeContribution: 92.3 },
    { name: 'Lime Juice', sugarPercentage: 1.35, volumeContribution: 90.8 },
    { name: 'Lychee', sugarPercentage: 16.1, volumeContribution: 81.8 },
    { name: 'Mango', sugarPercentage: 12.55, volumeContribution: 83.5 },
    { name: 'Maple Syrup', sugarPercentage: 66, volumeContribution: 32.2 },
    { name: 'Mulberry', sugarPercentage: 10.8, volumeContribution: 87.7 },
    { name: 'Nectarine', sugarPercentage: 7.76, volumeContribution: 87.6 },
    { name: 'Orange Juice', sugarPercentage: 9.39, volumeContribution: 88.5 },
    { name: 'Papaya', sugarPercentage: 7.11, volumeContribution: 88.1 },
    { name: 'Passionfruit', sugarPercentage: 11.15, volumeContribution: 72.9 },
    { name: 'Peaches', sugarPercentage: 8.53, volumeContribution: 88.3 },
    { name: 'Pear', sugarPercentage: 9.15, volumeContribution: 85.43 },
    { name: 'Persimmon', sugarPercentage: 13.25, volumeContribution: 80.3 },
    { name: 'Pineapple', sugarPercentage: 10.39, volumeContribution: 86 },
    { name: 'Plum', sugarPercentage: 9.86, volumeContribution: 87.2 },
    { name: 'Pomegranate', sugarPercentage: 12.6, volumeContribution: 77.9 },
    { name: 'Prickly Pear', sugarPercentage: 11, volumeContribution: 87.6 },
    { name: 'Prunes', sugarPercentage: 41.05, volumeContribution: 30.9 },
    { name: 'Raisins', sugarPercentage: 68.35, volumeContribution: 16.6 },
    { name: 'Raspberry', sugarPercentage: 4.98, volumeContribution: 85.8 },
    { name: 'Rhubarb', sugarPercentage: 1.03, volumeContribution: 93.6 },
    { name: 'Strawberry', sugarPercentage: 5.45, volumeContribution: 91 },
    { name: 'Tangerine', sugarPercentage: 8.58, volumeContribution: 85.2 },
    { name: 'Tomato', sugarPercentage: 2.7, volumeContribution: 94.33 },
    { name: 'Watermelon', sugarPercentage: 7.6, volumeContribution: 91.4 },
    { name: 'Custom', sugarPercentage: 0.0, volumeContribution: 0.0 },
];