export const yeastsDictionary = {
    "18-2007": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "50-90" },
    "1895C": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "60-89" },
    "71B": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 14, tempRange: "59-86" },
    "ALCHEMY I": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15.5, tempRange: "56-61" },
    "ALCHEMY II": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15.5, tempRange: "56-62" },
    "ALCHEMY III": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15.5, tempRange: "61-82" },
    "ALCHEMY IV": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15.5, tempRange: "61-82" },
    "AW4": { brand: "Mangrove Jack", nitrogenRequirement: "Low", abvTolerance: 14, tempRange: "61-75" },
    "BA11": { brand: "Lalvin", nitrogenRequirement: "High", abvTolerance: 16, tempRange: "59-77" },
    "BDX": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "64-86" },
    "BM 45": { brand: "Lalvin", nitrogenRequirement: "High", abvTolerance: 15, tempRange: "64-82" },
    "BM 4x4": { brand: "Lalvin", nitrogenRequirement: "High", abvTolerance: 16, tempRange: "64-82" },
    "BRL97": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "62-85" },
    "BV7": { brand: "Mangrove Jack", nitrogenRequirement: "Low", abvTolerance: 14, tempRange: "57-82" },
    "C": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 17, tempRange: "59-86" },
    "CL23": { brand: "Mangrove Jack", nitrogenRequirement: "Low", abvTolerance: 18, tempRange: "57-90" },
    "CLOS": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 17, tempRange: "57-90" },
    "Cotes des Blanc": { brand: "Red Star", nitrogenRequirement: "Medium", abvTolerance: "12-14", tempRange: "64-86" },
    "CR51": { brand: "Mangrove Jack", nitrogenRequirement: "High", abvTolerance: 14, tempRange: "61-75" },
    "CROSS EVOLUTION": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "58-68" },
    "CSM": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "59-90" },
    "CVRP": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "64-90" },
    "CVW5": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "57-82" },
    "CY17": { brand: "Mangrove Jack", nitrogenRequirement: "Low", abvTolerance: 14, tempRange: "61-75" },
    "CY3079 (BOURGOBLANC)": { brand: "Lalvin", nitrogenRequirement: "High", abvTolerance: 15, tempRange: "59-77" },
    "DV10": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 17, tempRange: "50-95" },
    "EC1118": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 18, tempRange: "50-86" },
    "EC1118 (ORGANIC)": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 18, tempRange: "50-90" },
    "ENOFERM AMH": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "68-86" },
    "ENOFERM SYRAH": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "59-90" },
    "EXOTICS MOSAIC": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15.5, tempRange: "64-83" },
    "EXOTICS NOVELLO": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15.5, tempRange: "64-82" },
    "FERMIVIN 3C": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 14, tempRange: "62-72" },
    "FERMIVIN 4F9": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15.5, tempRange: "57-68" },
    "FERMIVIN A33": { brand: "Lalvin", nitrogenRequirement: "High", abvTolerance: 15.5, tempRange: "72-86" },
    "FERMIVIN MT48": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "68-86" },
    "FERMIVIN PF6": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 14, tempRange: "54-75" },
    "Generic Beer Yeast": { brand: "Other", nitrogenRequirement: "Medium", abvTolerance: 12, tempRange: "50-65" },
    "ICV D21": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "61-86" },
    "ICV D254": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "54-82" },
    "ICV D47": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "60-82" },
    "ICV D80": { brand: "Lalvin", nitrogenRequirement: "High", abvTolerance: 16, tempRange: "59-82" },
    "ICV GRE": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "59-82" },
    "ICV OKAY": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 16, tempRange: "54-86" },
    "ICV SUNROSE": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "57-68" },
    "IOC BE FRUITS": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 14, tempRange: "54-75" },
    "IOC BE THIOLS": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "59-77" },
    "K1 V1116": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 18, tempRange: "50-95" },
    "Kveik Yeast": { brand: "Other", nitrogenRequirement: "Very High", abvTolerance: 12, tempRange: "70-100+" },
    "LEVULINE BRG": { brand: "Lalvin", nitrogenRequirement: "High", abvTolerance: 15, tempRange: "64-88" },
    "M02": { brand: "Mangrove Jack", nitrogenRequirement: "Low", abvTolerance: 17.5, tempRange: "54-82" },
    "M05": { brand: "Mangrove Jack", nitrogenRequirement: "Medium", abvTolerance: 18, tempRange: "59-86" },
    "M83": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "63-81" },
    "MA33": { brand: "Mangrove Jack", nitrogenRequirement: "Low", abvTolerance: 14, tempRange: "64-82" },
    "MSB": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 14.5, tempRange: "57-68" },
    "MT": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "59-90" },
    "NBC": { brand: "Lalvin", nitrogenRequirement: "Med-High", abvTolerance: 15, tempRange: "57-68" },
    "NT 116": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "54-83" },
    "NT 202": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "64-82" },
    "NT 50": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 16.5, tempRange: "57-82" },
    "OENOFERM BOUQUET": { brand: "Lalvin", nitrogenRequirement: "High", abvTolerance: 15, tempRange: "61-68" },
    "OENOFERM FREDDO": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "55-63" },
    "OENOFERM PINOTYPE": { brand: "Lalvin", nitrogenRequirement: "High", abvTolerance: 15, tempRange: "64-82" },
    "OENOFERM RIESLING": { brand: "Lalvin", nitrogenRequirement: "High", abvTolerance: 13, tempRange: "63-72" },
    "OENOFERM X-THIOL": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "55-72" },
    "OENOFERM X-TREME": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 17, tempRange: "50-63" },
    "Other High N Yeast": { brand: "Other", nitrogenRequirement: "High", abvTolerance: 12, tempRange: "55-70" },
    "Other Low N Yeast": { brand: "Other", nitrogenRequirement: "Low", abvTolerance: 12, tempRange: "55-70" },
    "Other Medium N Yeast": { brand: "Other", nitrogenRequirement: "Medium", abvTolerance: 12, tempRange: "55-70" },
    "PERSY": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 16, tempRange: "59-82" },
    "Premier Blanc": { brand: "Red Star", nitrogenRequirement: "Low", abvTolerance: 18, tempRange: "59-86" },
    "Premier Classique": { brand: "Red Star", nitrogenRequirement: "Low", abvTolerance: 13, tempRange: "59-86" },
    "Premier Cuvee": { brand: "Red Star", nitrogenRequirement: "Medium", abvTolerance: 18, tempRange: "45-95" },
    "Premier Rouge (Pasteur Red)": { brand: "Red Star", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "64-86" },
    "QA23": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 16, tempRange: "59-90" },
    "R-HST": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "50-86" },
    "R2": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "50-86" },
    "R56": { brand: "Mangrove Jack", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "64-82" },
    "RA17": { brand: "Lalvin", nitrogenRequirement: "High", abvTolerance: 15, tempRange: "61-84" },
    "RC212 (BOURGOROUGE)": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "60-86" },
    "RHÔNE 2056": { brand: "Lalvin", nitrogenRequirement: "High", abvTolerance: 16, tempRange: "59-82" },
    "RHÔNE 2226": { brand: "Lalvin", nitrogenRequirement: "High", abvTolerance: 18, tempRange: "59-82" },
    "RHÔNE 4600": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "56-72" },
    "RP15": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 17, tempRange: "68-86" },
    "SAUVY": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 14, tempRange: "57-68" },
    "SENSY": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "54-64" },
    "SN9": { brand: "Mangrove Jack", nitrogenRequirement: "Low", abvTolerance: 18, tempRange: "57-82" },
    "STEINBERGER": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 13, tempRange: "59-77" },
    "SVG": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "61-82" },
    "TANGO": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15.5, tempRange: "59-82" },
    "UVAFERM 43": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 17, tempRange: "55-95" },
    "UVAFERM CEG (EPERNAY II)": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 13.5, tempRange: "59-77" },
    "VIN 13": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 17, tempRange: "54-61" },
    "VIN 2000": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 15.5, tempRange: "55-61" },
    "VITIFERM ALBA FRIA (ORGANIC)": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "61-65" },
    "VITIFERM ESPIRIT (ORGANIC)": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "61-65" },
    "VITIFERM PINOT ALBA (ORGANIC)": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "65-68" },
    "VITIFERM RUBINO EXTRA (ORGANIC)": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 17, tempRange: "61-90" },
    "VITIFERM SAUVAGE (ORGANIC)": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "61-90" },
    "VITIFERM VULCANO (ORGANIC)": { brand: "Lalvin", nitrogenRequirement: "Low", abvTolerance: 16, tempRange: "61-90" },
    "VITILEVURE 3001": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "54-90" },
    "VITILEVURE 58W": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 14, tempRange: "54-77" },
    "VITILEVURE ELIXIR": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "57-77" },
    "VR21": { brand: "Mangrove Jack", nitrogenRequirement: "High", abvTolerance: 15, tempRange: "64-82" },
    "VRB": { brand: "Lalvin", nitrogenRequirement: "Medium", abvTolerance: 17, tempRange: "59-82" },
    "W15": { brand: "Lalvin", nitrogenRequirement: "High", abvTolerance: 16, tempRange: "50-81" }
};

export const yeastsArray = [
    { brand: "Lalvin", yeast: "18-2007", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "50-90" },
    { brand: "Lalvin", yeast: "1895C", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "60-89" },
    { brand: "Lalvin", yeast: "71B", nitrogenRequirement: "Low", abvTolerance: 14, tempRange: "59-86" },
    { brand: "Lalvin", yeast: "ALCHEMY I", nitrogenRequirement: "Medium", abvTolerance: 15.5, tempRange: "56-61" },
    { brand: "Lalvin", yeast: "ALCHEMY II", nitrogenRequirement: "Medium", abvTolerance: 15.5, tempRange: "56-62" },
    { brand: "Lalvin", yeast: "ALCHEMY III", nitrogenRequirement: "Medium", abvTolerance: 15.5, tempRange: "61-82" },
    { brand: "Lalvin", yeast: "ALCHEMY IV", nitrogenRequirement: "Medium", abvTolerance: 15.5, tempRange: "61-82" },
    { brand: "Mangrove Jack", yeast: "AW4", nitrogenRequirement: "Low", abvTolerance: 14, tempRange: "61-75" },
    { brand: "Lalvin", yeast: "BA11", nitrogenRequirement: "High", abvTolerance: 16, tempRange: "59-77" },
    { brand: "Lalvin", yeast: "BDX", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "64-86" },
    { brand: "Lalvin", yeast: "BM 45", nitrogenRequirement: "High", abvTolerance: 15, tempRange: "64-82" },
    { brand: "Lalvin", yeast: "BM 4x4", nitrogenRequirement: "High", abvTolerance: 16, tempRange: "64-82" },
    { brand: "Lalvin", yeast: "BRL97", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "62-85" },
    { brand: "Mangrove Jack", yeast: "BV7", nitrogenRequirement: "Low", abvTolerance: 14, tempRange: "57-82" },
    { brand: "Lalvin", yeast: "C", nitrogenRequirement: "Low", abvTolerance: 17, tempRange: "59-86" },
    { brand: "Mangrove Jack", yeast: "CL23", nitrogenRequirement: "Low", abvTolerance: 18, tempRange: "57-90" },
    { brand: "Lalvin", yeast: "CLOS", nitrogenRequirement: "Medium", abvTolerance: 17, tempRange: "57-90" },
    { brand: "Red Star", yeast: "Cotes des Blanc", nitrogenRequirement: "Medium", abvTolerance: "12-14", tempRange: "64-86" },
    { brand: "Mangrove Jack", yeast: "CR51", nitrogenRequirement: "High", abvTolerance: 14, tempRange: "61-75" },
    { brand: "Lalvin", yeast: "CROSS EVOLUTION", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "58-68" },
    { brand: "Lalvin", yeast: "CSM", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "59-90" },
    { brand: "Lalvin", yeast: "CVRP", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "64-90" },
    { brand: "Lalvin", yeast: "CVW5", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "57-82" },
    { brand: "Mangrove Jack", yeast: "CY17", nitrogenRequirement: "Low", abvTolerance: 14, tempRange: "61-75" },
    { brand: "Lalvin", yeast: "CY3079 (BOURGOBLANC)", nitrogenRequirement: "High", abvTolerance: 15, tempRange: "59-77" },
    { brand: "Lalvin", yeast: "DV10", nitrogenRequirement: "Low", abvTolerance: 17, tempRange: "50-95" },
    { brand: "Lalvin", yeast: "EC1118", nitrogenRequirement: "Low", abvTolerance: 18, tempRange: "50-86" },
    { brand: "Lalvin", yeast: "EC1118 (ORGANIC)", nitrogenRequirement: "Low", abvTolerance: 18, tempRange: "50-90" },
    { brand: "Lalvin", yeast: "ENOFERM AMH", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "68-86" },
    { brand: "Lalvin", yeast: "ENOFERM SYRAH", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "59-90" },
    { brand: "Lalvin", yeast: "EXOTICS MOSAIC", nitrogenRequirement: "Medium", abvTolerance: 15.5, tempRange: "64-83" },
    { brand: "Lalvin", yeast: "EXOTICS NOVELLO", nitrogenRequirement: "Medium", abvTolerance: 15.5, tempRange: "64-82" },
    { brand: "Lalvin", yeast: "FERMIVIN 3C", nitrogenRequirement: "Medium", abvTolerance: 14, tempRange: "62-72" },
    { brand: "Lalvin", yeast: "FERMIVIN 4F9", nitrogenRequirement: "Medium", abvTolerance: 15.5, tempRange: "57-68" },
    { brand: "Lalvin", yeast: "FERMIVIN A33", nitrogenRequirement: "High", abvTolerance: 15.5, tempRange: "72-86" },
    { brand: "Lalvin", yeast: "FERMIVIN MT48", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "68-86" },
    { brand: "Lalvin", yeast: "FERMIVIN PF6", nitrogenRequirement: "Medium", abvTolerance: 14, tempRange: "54-75" },
    { brand: "Other", yeast: "Generic Beer Yeast", nitrogenRequirement: "Medium", abvTolerance: 12, tempRange: "50-65" },
    { brand: "Lalvin", yeast: "ICV D21", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "61-86" },
    { brand: "Lalvin", yeast: "ICV D254", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "54-82" },
    { brand: "Lalvin", yeast: "ICV D47", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "60-82" },
    { brand: "Lalvin", yeast: "ICV D80", nitrogenRequirement: "High", abvTolerance: 16, tempRange: "59-82" },
    { brand: "Lalvin", yeast: "ICV GRE", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "59-82" },
    { brand: "Lalvin", yeast: "ICV OKAY", nitrogenRequirement: "Low", abvTolerance: 16, tempRange: "54-86" },
    { brand: "Lalvin", yeast: "ICV SUNROSE", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "57-68" },
    { brand: "Lalvin", yeast: "IOC BE FRUITS", nitrogenRequirement: "Low", abvTolerance: 14, tempRange: "54-75" },
    { brand: "Lalvin", yeast: "IOC BE THIOLS", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "59-77" },
    { brand: "Lalvin", yeast: "K1 V1116", nitrogenRequirement: "Low", abvTolerance: 18, tempRange: "50-95" },
    { brand: "Other", yeast: "Kveik Yeast", nitrogenRequirement: "Very High", abvTolerance: 12, tempRange: "70-100+" },
    { brand: "Lalvin", yeast: "LEVULINE BRG", nitrogenRequirement: "High", abvTolerance: 15, tempRange: "64-88" },
    { brand: "Mangrove Jack", yeast: "M02", nitrogenRequirement: "Low", abvTolerance: 17.5, tempRange: "54-82" },
    { brand: "Mangrove Jack", yeast: "M05", nitrogenRequirement: "Medium", abvTolerance: 18, tempRange: "59-86" },
    { brand: "Lalvin", yeast: "M83", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "63-81" },
    { brand: "Mangrove Jack", yeast: "MA33", nitrogenRequirement: "Low", abvTolerance: 14, tempRange: "64-82" },
    { brand: "Lalvin", yeast: "MSB", nitrogenRequirement: "Medium", abvTolerance: 14.5, tempRange: "57-68" },
    { brand: "Lalvin", yeast: "MT", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "59-90" },
    { brand: "Lalvin", yeast: "NBC", nitrogenRequirement: "Med-High", abvTolerance: 15, tempRange: "57-68" },
    { brand: "Lalvin", yeast: "NT 116", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "54-83" },
    { brand: "Lalvin", yeast: "NT 202", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "64-82" },
    { brand: "Lalvin", yeast: "NT 50", nitrogenRequirement: "Medium", abvTolerance: 16.5, tempRange: "57-82" },
    { brand: "Lalvin", yeast: "OENOFERM BOUQUET", nitrogenRequirement: "High", abvTolerance: 15, tempRange: "61-68" },
    { brand: "Lalvin", yeast: "OENOFERM FREDDO", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "55-63" },
    { brand: "Lalvin", yeast: "OENOFERM PINOTYPE", nitrogenRequirement: "High", abvTolerance: 15, tempRange: "64-82" },
    { brand: "Lalvin", yeast: "OENOFERM RIESLING", nitrogenRequirement: "High", abvTolerance: 13, tempRange: "63-72" },
    { brand: "Lalvin", yeast: "OENOFERM X-THIOL", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "55-72" },
    { brand: "Lalvin", yeast: "OENOFERM X-TREME", nitrogenRequirement: "Low", abvTolerance: 17, tempRange: "50-63" },
    { brand: "Other", yeast: "Other High N Yeast", nitrogenRequirement: "High", abvTolerance: 12, tempRange: "55-70" },
    { brand: "Other", yeast: "Other Low N Yeast", nitrogenRequirement: "Low", abvTolerance: 12, tempRange: "55-70" },
    { brand: "Other", yeast: "Other Medium N Yeast", nitrogenRequirement: "Medium", abvTolerance: 12, tempRange: "55-70" },
    { brand: "Lalvin", yeast: "PERSY", nitrogenRequirement: "Low", abvTolerance: 16, tempRange: "59-82" },
    { brand: "Red Star", yeast: "Premier Blanc", nitrogenRequirement: "Low", abvTolerance: 18, tempRange: "59-86" },
    { brand: "Red Star", yeast: "Premier Classique", nitrogenRequirement: "Low", abvTolerance: 13, tempRange: "59-86" },
    { brand: "Red Star", yeast: "Premier Cuvee", nitrogenRequirement: "Medium", abvTolerance: 18, tempRange: "45-95" },
    { brand: "Red Star", yeast: "Premier Rouge (Pasteur Red)", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "64-86" },
    { brand: "Lalvin", yeast: "QA23", nitrogenRequirement: "Low", abvTolerance: 16, tempRange: "59-90" },
    { brand: "Lalvin", yeast: "R-HST", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "50-86" },
    { brand: "Lalvin", yeast: "R2", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "50-86" },
    { brand: "Mangrove Jack", yeast: "R56", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "64-82" },
    { brand: "Lalvin", yeast: "RA17", nitrogenRequirement: "High", abvTolerance: 15, tempRange: "61-84" },
    { brand: "Lalvin", yeast: "RC212 (BOURGOROUGE)", nitrogenRequirement: "Medium", abvTolerance: 16, tempRange: "60-86" },
    { brand: "Lalvin", yeast: "RHÔNE 2056", nitrogenRequirement: "High", abvTolerance: 16, tempRange: "59-82" },
    { brand: "Lalvin", yeast: "RHÔNE 2226", nitrogenRequirement: "High", abvTolerance: 18, tempRange: "59-82" },
    { brand: "Lalvin", yeast: "RHÔNE 4600", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "56-72" },
    { brand: "Lalvin", yeast: "RP15", nitrogenRequirement: "Medium", abvTolerance: 17, tempRange: "68-86" },
    { brand: "Lalvin", yeast: "SAUVY", nitrogenRequirement: "Medium", abvTolerance: 14, tempRange: "57-68" },
    { brand: "Lalvin", yeast: "SENSY", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "54-64" },
    { brand: "Mangrove Jack", yeast: "SN9", nitrogenRequirement: "Low", abvTolerance: 18, tempRange: "57-82" },
    { brand: "Lalvin", yeast: "STEINBERGER", nitrogenRequirement: "Medium", abvTolerance: 13, tempRange: "59-77" },
    { brand: "Lalvin", yeast: "SVG", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "61-82" },
    { brand: "Lalvin", yeast: "TANGO", nitrogenRequirement: "Medium", abvTolerance: 15.5, tempRange: "59-82" },
    { brand: "Lalvin", yeast: "UVAFERM 43", nitrogenRequirement: "Low", abvTolerance: 17, tempRange: "55-95" },
    { brand: "Lalvin", yeast: "UVAFERM CEG (EPERNAY II)", nitrogenRequirement: "Medium", abvTolerance: 13.5, tempRange: "59-77" },
    { brand: "Lalvin", yeast: "VIN 13", nitrogenRequirement: "Low", abvTolerance: 17, tempRange: "54-61" },
    { brand: "Lalvin", yeast: "VIN 2000", nitrogenRequirement: "Low", abvTolerance: 15.5, tempRange: "55-61" },
    { brand: "Lalvin", yeast: "VITIFERM ALBA FRIA (ORGANIC)", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "61-65" },
    { brand: "Lalvin", yeast: "VITIFERM ESPIRIT (ORGANIC)", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "61-65" },
    { brand: "Lalvin", yeast: "VITIFERM PINOT ALBA (ORGANIC)", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "65-68" },
    { brand: "Lalvin", yeast: "VITIFERM RUBINO EXTRA (ORGANIC)", nitrogenRequirement: "Low", abvTolerance: 17, tempRange: "61-90" },
    { brand: "Lalvin", yeast: "VITIFERM SAUVAGE (ORGANIC)", nitrogenRequirement: "Low", abvTolerance: 15, tempRange: "61-90" },
    { brand: "Lalvin", yeast: "VITIFERM VULCANO (ORGANIC)", nitrogenRequirement: "Low", abvTolerance: 16, tempRange: "61-90" },
    { brand: "Lalvin", yeast: "VITILEVURE 3001", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "54-90" },
    { brand: "Lalvin", yeast: "VITILEVURE 58W", nitrogenRequirement: "Medium", abvTolerance: 14, tempRange: "54-77" },
    { brand: "Lalvin", yeast: "VITILEVURE ELIXIR", nitrogenRequirement: "Medium", abvTolerance: 15, tempRange: "57-77" },
    { brand: "Mangrove Jack", yeast: "VR21", nitrogenRequirement: "High", abvTolerance: 15, tempRange: "64-82" },
    { brand: "Lalvin", yeast: "VRB", nitrogenRequirement: "Medium", abvTolerance: 17, tempRange: "59-82" },
    { brand: "Lalvin", yeast: "W15", nitrogenRequirement: "High", abvTolerance: 16, tempRange: "50-81" }
];